export type TAutomationStatus =
  | "failed"
  | "finished"
  | "finished with warnings"
  | "must stop"
  | "not started"
  | "running"
  | "starting"
  | "stopped";

export type TAutomationState = "available" | "unavailable" | "disabled";

export interface IAutomationDetailResponseObject {
  data: object;
  guid: string;
  error: object;
  title: string;
  input: object;
  status: TAutomationStatus;
  context:
    | "test_run"
    | "editor"
    | "detail"
    | "api_sync"
    | "api_async"
    | "webhook"
    | "lookup";
  stopTime: string;
  createdAt: string;
  isTestRun: boolean;
  startTime: string;
  updatedAt: string;
  isArchived: boolean;
  expectedInputs: object;
  scheduledStartTime: string;
}

export interface IScheduleResponstObject {
  id: number;
  guid: string;
  stopAt: string;
  startAt: string;
  /**
   * Time in seconds
   */
  interval: number;
  timezone: string;
  lastStartedAt: string;
}

export interface IScheduleRequestObject {
  /**
   * Time in seconds
   */
  interval: number;
  stopAt: string;
  startAt: string;
  timezone: string;
}

export interface IAutomation {
  guid: string;
  state: TAutomationState;
  title: string;
  lastRun: IAutomationDetailResponseObject;
  ownerId: string;
  runMode: "manual" | "scheduled" | "triggered" | "webhook";
  createdAt: string;
  lastRunAt: string;
  schedules: IScheduleResponstObject[];
  updatedAt: string;
  /**
   * Workspace generated by the Qlik Application Automations editor
   */
  workspace: object;
  description: string;
  /**
   * A list of snippets used inside the workspace.
   */
  snippedGuids: string[];
  /**
   * A list of connectors used inside the workspace.
   */
  endpointGuids: string[];
  lastRunStatus: TAutomationStatus;
  /**
   * A list of connectors used inside the workspace.
   */
  connectorGuids: string[];
  executionToken: string;
}

export interface IAutomationCreate {
  name: string;
  state?: TAutomationState;
  workspace?: object;
  description?: string;
  schedule: IScheduleRequestObject[];
}
